# Demo Spring AzurePipeline

trigger:
  branches:
    include:
      - master
# Any pull request raise to this branch, run the pipeline
pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Java Unit test Stage'
    jobs:
    - job: 'JunitTest'
      displayName: 'Junit Test Job'
      steps:
      - script: echo 'Running Spring demo app unit test with iniline script'
      - task: Maven@4
        inputs:
          goals: 'clean test'
          codeCoverageToolOption: 'None'

      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco' 
  - stage: 'BuildArtifact'
    displayName: 'Building java artifacts'
    jobs:
    - job: 'BuildArtifact'
      displayName: 'Building java artifacts'
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          options: '--no-transfer-progress'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

